"""added backref logic for bet outcomes

Revision ID: 3462650e10c1
Revises: a0a1f1b9672b
Create Date: 2023-11-11 09:08:02.701189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3462650e10c1'
down_revision: Union[str, None] = 'a0a1f1b9672b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bet', 'bet_outcomes', ['outcome'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bet_outcome_fkey', 'bet', type_='foreignkey')
    # ### end Alembic commands ###
