"""added betting

Revision ID: a0a1f1b9672b
Revises: 73427d0ad7c9
Create Date: 2023-11-10 12:28:29.861780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.models.bet import Bet
from app.db.models.betEvent import BetEvent
from app.db.models.betOutcome import BetOutcome
from app.db.database import Engine

# revision identifiers, used by Alembic.
revision: str = 'a0a1f1b9672b'
down_revision: Union[str, None] = '73427d0ad7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    BetEvent.__table__.create(bind = Engine)
    Bet.__table__.create(bind = Engine)
    BetOutcome.__table__.create(bind = Engine)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Bet.__table__.drop(bind = Engine)
    BetOutcome.__table__.drop(bind = Engine)
    BetEvent.__table__.drop(bind = Engine)
    pass
    # ### end Alembic commands ###
